development:
  sessions:
    default:
      database: mongoid_criteria_filter_dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: mongoid_criteria_filter_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: mongoid_criteria_filter
      hosts:
        - localhost:27017